version: '3.8'

services:
  chatllama:
    build: .
    ports:
      - "${PORT:-8000}:${PORT:-8000}"
    environment:
      - PORT=${PORT:-8000}
    volumes:
      # Mount data directory for persistent SQLite database
      - ./data:/app/data
    restart: unless-stopped
    stop_grace_period: 30s
    healthcheck:
      test: ["CMD", "python", "-c", "import requests, os; requests.get(f'http://localhost:{os.environ.get(\"PORT\", 8000)}')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    deploy:
      resources:
        limits:
          memory: 8G
        reservations:
          memory: 4G